from __future__ import annotations

import math
from pathlib import Path

from app.adapters.file_project_voices import FileProjectVoices
from app.adapters.file_voice_model_sets import FileVoiceModelSets
from app.adapters.file_voice_outputs import FileVoiceOutputs
from app.adapters.gpu_lease import GpuLease
from app.domain.models import SpeakerSimilarityGateEvidence, VoiceModelSet, VoiceModelSetGateRequest
from app.domain.ports import ProjectRepository, SpeakerEmbedder


class SpeakerSimilarityGate:
    """Fail-closed publication gate over project-owned voice outputs."""

    def __init__(
        self,
        projects: ProjectRepository,
        voices: FileProjectVoices,
        outputs: FileVoiceOutputs,
        sets: FileVoiceModelSets,
        embedders: dict[str, SpeakerEmbedder],
        gpu_lease: GpuLease | None = None,
    ) -> None:
        self.projects = projects
        self.voices = voices
        self.outputs = outputs
        self.sets = sets
        self.embedders = embedders
        self.gpu_lease = gpu_lease

    def evaluate(self, project_id: str, set_id: str, request: VoiceModelSetGateRequest) -> VoiceModelSet:
        model_set = self.sets.get(project_id, set_id)
        if model_set.status == "published":
            return model_set
        if request.embedder_id is None:
            raise ValueError("A Speaker Embedder must be selected.")
        embedder = self.embedders.get(request.embedder_id)
        if embedder is None:
            raise KeyError(request.embedder_id)
        if not embedder.info.available:
            raise RuntimeError(embedder.info.status)
        expected = set(model_set.voice_ids)
        supplied = set(request.output_ids_by_voice_id)
        if supplied != expected:
            raise ValueError("Gate requires exactly one output for every Voice Model in the set.")

        anchor = self.voices.get(project_id, model_set.anchor_voice_id)
        reference = self.voices.absolute(project_id, anchor.reference_audio)
        candidates: dict[str, Path] = {}
        for voice_id, output_id in request.output_ids_by_voice_id.items():
            output = self.outputs.get(project_id, output_id)
            if output.voice_id != voice_id:
                raise ValueError(f"Voice Output {output_id} was not generated by {voice_id}.")
            candidates[voice_id] = self.outputs.audio_path(project_id, output_id)

        holder = self.gpu_lease.acquire("Speaker identity gate") if self.gpu_lease else None
        try:
            scores = embedder.compare(reference, candidates)
        finally:
            if holder is not None:
                self.gpu_lease.release(holder.token)  # type: ignore[union-attr]
        if set(scores) != expected or any(not math.isfinite(score) or not -1 <= score <= 1 for score in scores.values()):
            raise RuntimeError("Speaker embedder returned incomplete or invalid similarity scores.")

        score_passed = all(score >= embedder.info.threshold for score in scores.values())
        passed = score_passed and embedder.info.calibrated
        reason = "passed" if passed else ("threshold-unmeasured" if score_passed else "below-threshold")
        evidence = SpeakerSimilarityGateEvidence(
            embedder_id=embedder.info.id,
            embedder_revision=embedder.info.revision,
            threshold=embedder.info.threshold,
            calibrated=embedder.info.calibrated,
            scores_by_voice_id=scores,
            candidate_output_ids_by_voice_id=request.output_ids_by_voice_id,
            score_passed=score_passed,
            passed=passed,
            decision_reason=reason,
        )
        return self.sets.record_gate(project_id, set_id, evidence)
